In [364]:
import pandas as pd
import numpy as np

#vizilation

import matplotlib.pyplot as plt
from plotly.subplots import make_subplots
import plotly.express as px
import plotly.graph_objects as go
import matplotlib.pyplot as plt 
import seaborn as sns 

#models

from sklearn.preprocessing import OneHotEncoder,LabelEncoder
from sklearn.model_selection import train_test_split
from sklearn.metrics import confusion_matrix,mean_squared_error,classification_report
from sklearn.linear_model import LogisticRegression
from sklearn.svm import LinearSVC
from sklearn.naive_bayes import GaussianNB



In [365]:
df=pd.read_csv("train.csv")

df

PassengerId  Survived  Pclass  \
0              1         0       3   
1              2         1       1   
2              3         1       3   
3              4         1       1   
4              5         0       3   
..           ...       ...     ...   
886          887         0       2   
887          888         1       1   
888          889         0       3   
889          890         1       1   
890          891         0       3   

                                                  Name     Sex   Age  SibSp  \
0                              Braund, Mr. Owen Harris    male  22.0      1   
1    Cumings, Mrs. John Bradley (Florence Briggs Th...  female  38.0      1   
2                               Heikkinen, Miss. Laina  female  26.0      0   
3         Futrelle, Mrs. Jacques Heath (Lily May Peel)  female  35.0      1   
4                             Allen, Mr. William Henry    male  35.0      0   
..                                                 ...     ...   ...    ...   
886                              Montvila, Rev. Juozas    male  27.0      0   
887                       Graham, Miss. Margaret Edith  female  19.0      0   
888           Johnston, Miss. Catherine Helen "Carrie"  female   NaN      1   
889                              Behr, Mr. Karl Howell    male  26.0      0   
890                                Dooley, Mr. Patrick    male  32.0      0   

     Parch            Ticket     Fare Cabin Embarked  
0        0         A/5 21171   7.2500   NaN        S  
1        0          PC 17599  71.2833   C85        C  
2        0  STON/O2. 3101282   7.9250   NaN        S  
3        0            113803  53.1000  C123        S  
4        0            373450   8.0500   NaN        S  
..     ...               ...      ...   ...      ...  
886      0            211536  13.0000   NaN        S  
887      0            112053  30.0000   B42        S  
888      2        W./C. 6607  23.4500   NaN        S  
889      0            111369  30.0000  C148        C  
890      0            370376   7.7500   NaN        Q  

[891 rows x 12 columns]

In [366]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 891 entries, 0 to 890
Data columns (total 12 columns):
 #   Column       Non-Null Count  Dtype  
---  ------       --------------  -----  
 0   PassengerId  891 non-null    int64  
 1   Survived     891 non-null    int64  
 2   Pclass       891 non-null    int64  
 3   Name         891 non-null    object 
 4   Sex          891 non-null    object 
 5   Age          714 non-null    float64
 6   SibSp        891 non-null    int64  
 7   Parch        891 non-null    int64  
 8   Ticket       891 non-null    object 
 9   Fare         891 non-null    float64
 10  Cabin        204 non-null    object 
 11  Embarked     889 non-null    object 
dtypes: float64(2), int64(5), object(5)
memory usage: 83.7+ KB


In [367]:
df.describe()

PassengerId    Survived      Pclass         Age       SibSp  \
count   891.000000  891.000000  891.000000  714.000000  891.000000   
mean    446.000000    0.383838    2.308642   29.699118    0.523008   
std     257.353842    0.486592    0.836071   14.526497    1.102743   
min       1.000000    0.000000    1.000000    0.420000    0.000000   
25%     223.500000    0.000000    2.000000   20.125000    0.000000   
50%     446.000000    0.000000    3.000000   28.000000    0.000000   
75%     668.500000    1.000000    3.000000   38.000000    1.000000   
max     891.000000    1.000000    3.000000   80.000000    8.000000   

            Parch        Fare  
count  891.000000  891.000000  
mean     0.381594   32.204208  
std      0.806057   49.693429  
min      0.000000    0.000000  
25%      0.000000    7.910400  
50%      0.000000   14.454200  
75%      0.000000   31.000000  
max      6.000000  512.329200

In [368]:
df.isnull().sum()

PassengerId      0
Survived         0
Pclass           0
Name             0
Sex              0
Age            177
SibSp            0
Parch            0
Ticket           0
Fare             0
Cabin          687
Embarked         2
dtype: int64

In [369]:
df.drop("Cabin",axis=1,inplace=True)

In [370]:
df.isnull().sum()

PassengerId      0
Survived         0
Pclass           0
Name             0
Sex              0
Age            177
SibSp            0
Parch            0
Ticket           0
Fare             0
Embarked         2
dtype: int64

In [371]:
df["Embarked"]=df["Embarked"].fillna("U")

In [372]:
df.isnull().sum()

PassengerId      0
Survived         0
Pclass           0
Name             0
Sex              0
Age            177
SibSp            0
Parch            0
Ticket           0
Fare             0
Embarked         0
dtype: int64

In [373]:
df[df['Sex'] == 'female'] = df[df['Sex'] == 'female'].fillna(np.round(df[df['Sex'] == 'female']["Age"].mean(),2))


In [374]:
df.isnull().sum()

PassengerId      0
Survived         0
Pclass           0
Name             0
Sex              0
Age            124
SibSp            0
Parch            0
Ticket           0
Fare             0
Embarked         0
dtype: int64

In [375]:
df[df['Sex'] == 'male'] = df[df['Sex'] == 'male'].fillna(np.round(df[df['Sex'] == 'male']["Age"].mean(),2))


In [376]:
df.isnull().sum()

PassengerId    0
Survived       0
Pclass         0
Name           0
Sex            0
Age            0
SibSp          0
Parch          0
Ticket         0
Fare           0
Embarked       0
dtype: int64

In [377]:
df

PassengerId  Survived  Pclass  \
0              1         0       3   
1              2         1       1   
2              3         1       3   
3              4         1       1   
4              5         0       3   
..           ...       ...     ...   
886          887         0       2   
887          888         1       1   
888          889         0       3   
889          890         1       1   
890          891         0       3   

                                                  Name     Sex    Age  SibSp  \
0                              Braund, Mr. Owen Harris    male  22.00      1   
1    Cumings, Mrs. John Bradley (Florence Briggs Th...  female  38.00      1   
2                               Heikkinen, Miss. Laina  female  26.00      0   
3         Futrelle, Mrs. Jacques Heath (Lily May Peel)  female  35.00      1   
4                             Allen, Mr. William Henry    male  35.00      0   
..                                                 ...     ...    ...    ...   
886                              Montvila, Rev. Juozas    male  27.00      0   
887                       Graham, Miss. Margaret Edith  female  19.00      0   
888           Johnston, Miss. Catherine Helen "Carrie"  female  27.92      1   
889                              Behr, Mr. Karl Howell    male  26.00      0   
890                                Dooley, Mr. Patrick    male  32.00      0   

     Parch            Ticket     Fare Embarked  
0        0         A/5 21171   7.2500        S  
1        0          PC 17599  71.2833        C  
2        0  STON/O2. 3101282   7.9250        S  
3        0            113803  53.1000        S  
4        0            373450   8.0500        S  
..     ...               ...      ...      ...  
886      0            211536  13.0000        S  
887      0            112053  30.0000        S  
888      2        W./C. 6607  23.4500        S  
889      0            111369  30.0000        C  
890      0            370376   7.7500        Q  

[891 rows x 11 columns]

In [378]:
passengerId=df["PassengerId"].value_counts().sort_values(ascending=False)


In [379]:
Survived=df["Survived"].value_counts()

In [380]:
fig=px.bar(
    x=Survived.index.astype(str),
    y=Survived.values,
    color=Survived.index,
    text=Survived.values
   
)
    
fig.update_layout(
    title="Survived people",
    template="plotly_dark"
)
fig.show()
    

In [381]:
fig=px.bar(
    x=passengerId.index.astype(str),
    y=passengerId.values,
    
    text=passengerId.values
   
)
    
fig.update_layout(
    title="passengerId",
    template="plotly_dark"
)
fig.show()

In [382]:
Pclass=df["Pclass"].value_counts().sort_values(ascending=False)

In [383]:
fig=px.pie(df,
    names=["3","1","2"],
    values=Pclass.values,
    color=["blue","white","brown"]
)

fig.update_layout(
    title="Pclass",
    template="plotly_dark"
)

fig.show()

In [384]:
Name=df["Name"].value_counts()

In [385]:
fig=px.bar(
    x=Name.index,
    y=Name.values,
    
    text=Name.values
   
)
    
fig.update_layout(
    title="Name",
    template="plotly_dark",
    xaxis=dict(
        title="Name"
    ),
    yaxis=dict(
        title="sumName"
    )
)
fig.show()

isim ve passengerId unique degerler 

In [386]:
df.drop(["Name","PassengerId"],axis=1,inplace=True)

In [387]:
Sex=df["Sex"].value_counts()
femaleDf=df.loc[df["Sex"]=="female"]
maleDf=df.loc[df["Sex"]=="male"]


In [388]:
fig=make_subplots(rows=1,cols=2)
fig.add_trace(go.Box(y=femaleDf["Age"],name="female Age",marker_color="MediumPurple"),row=1,col=1)
fig.add_trace(go.Box(y=maleDf["Age"],name="male Age",marker_color="MediumPurple"),row=1,col=1)

fig.add_trace(go.Bar(x=Sex.index,y=Sex.values,name="female and male counts",marker_color="MediumPurple"),row=1,col=2)
fig.update_layout(template="plotly_dark")
fig.show()

In [389]:
femaleDf.loc[df["Age"]>=56]["Survived"].value_counts()

Survived
1    8
0    1
Name: count, dtype: int64

In [390]:
SibSp=df["SibSp"].value_counts().sort_values(ascending=False)
Parch=df["Parch"].value_counts().sort_values(ascending=False)
Fare=df["Fare"].value_counts().sort_values(ascending=False)

In [391]:
fig=make_subplots(rows=2,cols=2)
fig.add_trace(go.Box(y=df["Fare"],name="FareBox",marker_color="MediumPurple"),row=1,col=1)
fig.add_trace(go.Histogram(x=df["Fare"],name="FareHistogram",marker_color="MediumPurple"),row=1,col=2)

fig.add_trace(go.Bar(x=SibSp.index,y=SibSp.values,name="SibSp counts",marker_color="MediumPurple"),row=2,col=1)
fig.add_trace(go.Bar(x=Parch.index,y=Parch.values,name="Parch counts",marker_color="MediumPurple"),row=2,col=2)

fig.update_layout(template="plotly_dark")
fig.show()

165K dan sonrasi veri setinden atilabilir cunku arada bosluk cok -- 3-4-5 parch lar atilabilir 

In [392]:
uniqueValueSum=len(df['Ticket'].unique())
uniqueValueSum

681

ayni biletle farkli kisilerde gemiye binmis oldugunu goruyoruz


In [393]:
embarked=df["Embarked"].value_counts()

In [394]:
fig=px.bar(
    x=embarked.index,
    y=embarked.values,
    color=embarked.values,
    text=embarked.values,
    color_continuous_scale="OrRd"
)
fig.update_layout(
    title="Embarked",
    template="plotly_dark"
)
fig.show()

In [395]:
PclassAndSurvived=df.groupby("Pclass")["Survived"].mean()

In [396]:
PclassAndSurvived

Pclass
1    0.629630
2    0.472826
3    0.242363
Name: Survived, dtype: float64

In [397]:
fig=px.bar(
    x=PclassAndSurvived.index.astype(str),
    y=PclassAndSurvived.values,
    color=PclassAndSurvived.values,
    text=PclassAndSurvived.values,
    color_continuous_scale="OrRd"
)
fig.update_layout(
    title="Pclass And Survived",
    template="plotly_dark",
    xaxis=dict(
        title="Pclass"
    ),
    yaxis=dict(
        title="Survived mean"
    )
    
)
fig.show()


In [398]:
df

Survived  Pclass     Sex    Age  SibSp  Parch            Ticket     Fare  \
0           0       3    male  22.00      1      0         A/5 21171   7.2500   
1           1       1  female  38.00      1      0          PC 17599  71.2833   
2           1       3  female  26.00      0      0  STON/O2. 3101282   7.9250   
3           1       1  female  35.00      1      0            113803  53.1000   
4           0       3    male  35.00      0      0            373450   8.0500   
..        ...     ...     ...    ...    ...    ...               ...      ...   
886         0       2    male  27.00      0      0            211536  13.0000   
887         1       1  female  19.00      0      0            112053  30.0000   
888         0       3  female  27.92      1      2        W./C. 6607  23.4500   
889         1       1    male  26.00      0      0            111369  30.0000   
890         0       3    male  32.00      0      0            370376   7.7500   

    Embarked  
0          S  
1          C  
2          S  
3          S  
4          S  
..       ...  
886        S  
887        S  
888        S  
889        C  
890        Q  

[891 rows x 9 columns]

In [399]:
SexAndSurvived=df.groupby("Sex")["Survived"].mean()

In [400]:
fig=px.bar(
    x=SexAndSurvived.index.astype(str),
    y=SexAndSurvived.values,
    color=SexAndSurvived.values,
    text=SexAndSurvived.values,
    color_continuous_scale="OrRd"
)
fig.update_layout(
    title="SEx And Survived",
    template="plotly_dark",
    xaxis=dict(
        title="Sex"
    ),
    yaxis=dict(
        title="Survived mean"
    )
    
)
fig.show()

In [401]:
AgeAndSurvivedFemale=femaleDf.groupby("Survived")["Age"].mean()
AgeAndSurvivedmale=maleDf.groupby("Survived")["Age"].mean()
AgeAndSurvivedmale

Survived
0    31.413120
1    27.783028
Name: Age, dtype: float64

In [402]:
AgeAndSurvivedFemale

Survived
0    25.649877
1    28.704378
Name: Age, dtype: float64

In [403]:
fig=make_subplots(rows=1,cols=1)
fig.add_trace(go.Bar(y=AgeAndSurvivedFemale.values,x=AgeAndSurvivedFemale.index,name="female Age",marker_color="MediumPurple"),row=1,col=1)
fig.add_trace(go.Bar(y=AgeAndSurvivedmale.values,x=AgeAndSurvivedmale.index,name="male Age",marker_color="MediumPurple"),row=1,col=1)
fig.update_layout(
    title="Age Mean and survived ",
    template="plotly_dark",
    xaxis=dict(
        title="Survived"
    ),
    yaxis=dict(
        title="female and male AgeMean"
    )
    
)
fig.show()

In [404]:
SibSpSurvived=df.groupby("SibSp")["Survived"].mean()
ParchSurvived=df.groupby("Parch")["Survived"].mean().sort_values(ascending=False)
FareSurvived=df.groupby("Survived")["Fare"].mean().sort_values(ascending=False)


In [405]:
fig=make_subplots(rows=2,cols=2)
fig.add_trace(go.Bar(x=FareSurvived.index,y=FareSurvived.values,name="Fare and survived",marker_color="MediumPurple"),row=1,col=1)

fig.add_trace(go.Bar(x=SibSpSurvived.index,y=SibSpSurvived.values,name="SibSp and survived",marker_color="White"),row=2,col=1)
fig.add_trace(go.Bar(x=SibSpSurvived.index,y=SibSpSurvived.values,name="Parch and survived",marker_color="Red"),row=2,col=2)

fig.update_layout(template="plotly_dark")
fig.show()

In [406]:
df[df["Fare"]==0]

Survived  Pclass   Sex    Age  SibSp  Parch  Ticket  Fare Embarked
179         0       3  male  36.00      0      0    LINE   0.0        S
263         0       1  male  40.00      0      0  112059   0.0        S
271         1       3  male  25.00      0      0    LINE   0.0        S
277         0       2  male  30.73      0      0  239853   0.0        S
302         0       3  male  19.00      0      0    LINE   0.0        S
413         0       2  male  30.73      0      0  239853   0.0        S
466         0       2  male  30.73      0      0  239853   0.0        S
481         0       2  male  30.73      0      0  239854   0.0        S
597         0       3  male  49.00      0      0    LINE   0.0        S
633         0       1  male  30.73      0      0  112052   0.0        S
674         0       2  male  30.73      0      0  239856   0.0        S
732         0       2  male  30.73      0      0  239855   0.0        S
806         0       1  male  39.00      0      0  112050   0.0        S
815         0       1  male  30.73      0      0  112058   0.0        S
822         0       1  male  38.00      0      0   19972   0.0        S

In [407]:
df.drop(271,axis=0,inplace=True)

In [408]:
df[df.duplicated(subset="Ticket", keep=False)]

Survived  Pclass     Sex    Age  SibSp  Parch      Ticket     Fare  \
3           1       1  female  35.00      1      0      113803  53.1000   
7           0       3    male   2.00      3      1      349909  21.0750   
8           1       3  female  27.00      0      2      347742  11.1333   
9           1       2  female  14.00      1      0      237736  30.0708   
10          1       3  female   4.00      1      1     PP 9549  16.7000   
..        ...     ...     ...    ...    ...    ...         ...      ...   
876         0       3    male  20.00      0      0        7534   9.8458   
879         1       1  female  56.00      0      1       11767  83.1583   
880         1       2  female  25.00      0      1      230433  26.0000   
885         0       3  female  39.00      0      5      382652  29.1250   
888         0       3  female  27.92      1      2  W./C. 6607  23.4500   

    Embarked  
3          S  
7          S  
8          S  
9          C  
10         S  
..       ...  
876        S  
879        C  
880        S  
885        Q  
888        S  

[343 rows x 9 columns]

In [409]:
df[df["Ticket"]=="W./C. 6607"]

Survived  Pclass     Sex    Age  SibSp  Parch      Ticket   Fare Embarked
783         0       3    male  30.73      1      2  W./C. 6607  23.45        S
888         0       3  female  27.92      1      2  W./C. 6607  23.45        S

herkesin ticketi var kardesi ya da cocugu olanlar ayni bilete sahip olabiliyor o yuzden ticketi cikariyorum veri setinden

In [410]:
df.drop("Ticket",axis=1,inplace=True)

In [411]:
df

Survived  Pclass     Sex    Age  SibSp  Parch     Fare Embarked
0           0       3    male  22.00      1      0   7.2500        S
1           1       1  female  38.00      1      0  71.2833        C
2           1       3  female  26.00      0      0   7.9250        S
3           1       1  female  35.00      1      0  53.1000        S
4           0       3    male  35.00      0      0   8.0500        S
..        ...     ...     ...    ...    ...    ...      ...      ...
886         0       2    male  27.00      0      0  13.0000        S
887         1       1  female  19.00      0      0  30.0000        S
888         0       3  female  27.92      1      2  23.4500        S
889         1       1    male  26.00      0      0  30.0000        C
890         0       3    male  32.00      0      0   7.7500        Q

[890 rows x 8 columns]

In [412]:
cevir=LabelEncoder()
df["Sex"]=cevir.fit_transform(df["Sex"])

In [413]:
df

Survived  Pclass  Sex    Age  SibSp  Parch     Fare Embarked
0           0       3    1  22.00      1      0   7.2500        S
1           1       1    0  38.00      1      0  71.2833        C
2           1       3    0  26.00      0      0   7.9250        S
3           1       1    0  35.00      1      0  53.1000        S
4           0       3    1  35.00      0      0   8.0500        S
..        ...     ...  ...    ...    ...    ...      ...      ...
886         0       2    1  27.00      0      0  13.0000        S
887         1       1    0  19.00      0      0  30.0000        S
888         0       3    0  27.92      1      2  23.4500        S
889         1       1    1  26.00      0      0  30.0000        C
890         0       3    1  32.00      0      0   7.7500        Q

[890 rows x 8 columns]

In [414]:
df["Embarked"]=cevir.fit_transform(df["Embarked"])

# MODEL

In [415]:
train,test=train_test_split(df,test_size=0.2,random_state=42)

In [416]:
train

Survived  Pclass  Sex    Age  SibSp  Parch     Fare  Embarked
709         1       3    1  30.73      1      1  15.2458         0
239         0       2    1  33.00      0      0  12.2750         2
382         0       3    1  32.00      0      0   7.9250         2
793         0       1    1  30.73      0      0  30.6958         0
673         1       2    1  31.00      0      0  13.0000         2
..        ...     ...  ...    ...    ...    ...      ...       ...
106         1       3    0  21.00      0      0   7.6500         2
270         0       1    1  30.73      0      0  31.0000         2
861         0       2    1  21.00      1      0  11.5000         2
436         0       3    0  21.00      2      2  34.3750         2
102         0       1    1  21.00      0      1  77.2875         2

[712 rows x 8 columns]

In [417]:
test

Survived  Pclass  Sex    Age  SibSp  Parch      Fare  Embarked
281         0       3    1  28.00      0      0    7.8542         2
435         1       1    0  14.00      1      2  120.0000         2
39          1       3    0  14.00      1      0   11.2417         0
418         0       2    1  30.00      0      0   13.0000         2
586         0       2    1  47.00      0      0   15.0000         2
..        ...     ...  ...    ...    ...    ...       ...       ...
433         0       3    1  17.00      0      0    7.1250         2
773         0       3    1  30.73      0      0    7.2250         0
25          1       3    0  38.00      1      5   31.3875         2
84          1       2    0  17.00      0      0   10.5000         2
10          1       3    0   4.00      1      1   16.7000         2

[178 rows x 8 columns]

In [418]:
trainx=train.drop("Survived",axis=1)
trainy=train.loc[:,"Survived"]

In [419]:
testx=test.drop("Survived",axis=1)
testy=test.loc[:,"Survived"]

In [420]:
logisticRegression=LogisticRegression()
model1=logisticRegression.fit(trainx,trainy)
predict=model1.predict(testx)
predict

array([0, 1, 1, 0, 0, 0, 0, 1, 0, 0, 1, 1, 1, 0, 0, 0, 0, 0, 1, 1, 0, 0,
       0, 1, 0, 0, 0, 1, 0, 0, 0, 1, 0, 0, 0, 1, 1, 0, 1, 0, 0, 0, 0, 0,
       0, 1, 1, 0, 1, 1, 0, 1, 0, 1, 1, 1, 1, 0, 0, 1, 0, 1, 1, 0, 0, 0,
       0, 0, 1, 1, 0, 1, 1, 0, 0, 0, 1, 1, 0, 0, 0, 1, 1, 0, 0, 0, 0, 0,
       1, 0, 0, 1, 1, 0, 0, 0, 0, 0, 0, 1, 0, 0, 1, 0, 1, 1, 1, 1, 1, 1,
       0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 1, 1, 0, 1, 1, 1, 0, 0, 1, 0, 0, 0,
       0, 0, 1, 1, 0, 1, 1, 0, 0, 1, 1, 1, 1, 1, 0, 1, 0, 1, 0, 1, 1, 0,
       1, 0, 1, 0, 1, 1, 0, 1, 1, 0, 0, 0, 1, 0, 0, 1, 1, 0, 1, 0, 0, 0,
       1, 1])

In [421]:
confusion_matrix(predict,testy)

array([[87, 14],
       [15, 62]])

In [422]:
print(classification_report(predict,testy))

              precision    recall  f1-score   support

           0       0.85      0.86      0.86       101
           1       0.82      0.81      0.81        77

    accuracy                           0.84       178
   macro avg       0.83      0.83      0.83       178
weighted avg       0.84      0.84      0.84       178



In [423]:
LinearSVC=LinearSVC()
model2=LinearSVC.fit(trainx,trainy)
predictLinearSVC=model2.predict(testx)
predictLinearSVC

/home/eray/anaconda3/lib/python3.11/site-packages/sklearn/svm/_classes.py:32: FutureWarning:

The default value of `dual` will change from `True` to `'auto'` in 1.5. Set the value of `dual` explicitly to suppress the warning.

/home/eray/anaconda3/lib/python3.11/site-packages/sklearn/svm/_base.py:1242: ConvergenceWarning:

Liblinear failed to converge, increase the number of iterations.



array([0, 1, 1, 0, 0, 0, 0, 1, 0, 0, 1, 1, 1, 0, 0, 0, 0, 0, 1, 1, 0, 0,
       0, 1, 0, 1, 0, 1, 0, 0, 1, 1, 0, 0, 0, 1, 1, 0, 1, 0, 0, 0, 0, 0,
       0, 1, 1, 1, 1, 1, 0, 1, 0, 1, 1, 1, 1, 0, 0, 1, 0, 1, 1, 0, 0, 0,
       0, 0, 1, 1, 0, 1, 1, 0, 0, 0, 1, 1, 0, 0, 1, 1, 1, 0, 0, 0, 0, 1,
       1, 0, 0, 1, 1, 0, 0, 0, 0, 0, 0, 1, 0, 1, 1, 0, 1, 1, 1, 1, 1, 1,
       0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 1, 1, 0, 1, 1, 1, 0, 0, 1, 0, 0, 0,
       0, 0, 1, 1, 0, 1, 1, 0, 1, 1, 1, 1, 1, 1, 0, 1, 0, 1, 0, 1, 1, 0,
       1, 0, 1, 0, 1, 1, 0, 1, 1, 0, 0, 0, 1, 0, 0, 1, 1, 0, 1, 0, 0, 1,
       1, 1])

In [424]:
confusion_matrix(predictLinearSVC,testy)

array([[82, 11],
       [20, 65]])

In [425]:
print(classification_report(predictLinearSVC,testy))

              precision    recall  f1-score   support

           0       0.80      0.88      0.84        93
           1       0.86      0.76      0.81        85

    accuracy                           0.83       178
   macro avg       0.83      0.82      0.82       178
weighted avg       0.83      0.83      0.82       178



In [426]:
GaussianNB=GaussianNB()
model3=GaussianNB.fit(trainx,trainy)
predictGaussianNB=model3.predict(testx)
predictGaussianNB

array([0, 1, 1, 0, 0, 0, 0, 1, 0, 0, 1, 1, 1, 0, 0, 0, 0, 0, 1, 1, 0, 0,
       0, 1, 0, 1, 0, 1, 0, 0, 0, 1, 0, 0, 0, 1, 1, 0, 1, 0, 0, 0, 0, 0,
       0, 1, 1, 1, 1, 1, 0, 1, 0, 1, 1, 1, 1, 0, 0, 1, 0, 1, 1, 0, 0, 0,
       0, 0, 1, 1, 0, 1, 1, 0, 0, 0, 1, 1, 0, 0, 1, 1, 1, 0, 0, 0, 0, 1,
       1, 0, 0, 1, 1, 0, 0, 0, 0, 0, 0, 1, 0, 0, 1, 0, 1, 1, 1, 1, 1, 1,
       0, 1, 0, 1, 0, 1, 0, 0, 0, 0, 1, 1, 0, 1, 1, 1, 0, 0, 1, 0, 0, 0,
       1, 1, 1, 1, 0, 1, 1, 0, 1, 1, 1, 1, 1, 1, 0, 1, 0, 1, 0, 1, 1, 0,
       1, 0, 1, 0, 1, 1, 0, 1, 1, 0, 1, 0, 1, 0, 0, 1, 1, 0, 1, 0, 0, 0,
       1, 1])

In [427]:
confusion_matrix(predictGaussianNB,testy)

array([[79, 12],
       [23, 64]])

In [428]:
print(classification_report(predictGaussianNB,testy))

              precision    recall  f1-score   support

           0       0.77      0.87      0.82        91
           1       0.84      0.74      0.79        87

    accuracy                           0.80       178
   macro avg       0.81      0.80      0.80       178
weighted avg       0.81      0.80      0.80       178



In [429]:
def find_outliers_IQR(df):
    q1=df.quantile(0.25)
    q3=df.quantile(0.75)
    IQR=q3-q1
    outliers = df[((df<(q1-1.5*IQR)) | (df>(q3+1.5*IQR)))].index.tolist()
    
    print(outliers)
    print("Number of Outliers: ", len(outliers))
    return outliers


In [430]:
outliers=find_outliers_IQR(df["Fare"])

[1, 27, 31, 34, 52, 61, 62, 72, 88, 102, 118, 120, 124, 139, 151, 159, 180, 195, 201, 215, 218, 224, 230, 245, 256, 257, 258, 262, 268, 269, 275, 290, 291, 297, 299, 305, 306, 307, 310, 311, 318, 319, 324, 325, 332, 334, 336, 337, 341, 366, 369, 373, 375, 377, 380, 385, 390, 393, 412, 435, 438, 445, 453, 484, 486, 496, 498, 504, 505, 520, 527, 537, 540, 544, 550, 557, 558, 581, 585, 587, 591, 609, 627, 641, 645, 655, 659, 660, 665, 679, 681, 689, 698, 700, 708, 716, 730, 737, 741, 742, 745, 759, 763, 765, 779, 789, 792, 802, 820, 829, 835, 846, 849, 856, 863, 879]
Number of Outliers:  116


In [431]:
myDf=df
myDf

Survived  Pclass  Sex    Age  SibSp  Parch     Fare  Embarked
0           0       3    1  22.00      1      0   7.2500         2
1           1       1    0  38.00      1      0  71.2833         0
2           1       3    0  26.00      0      0   7.9250         2
3           1       1    0  35.00      1      0  53.1000         2
4           0       3    1  35.00      0      0   8.0500         2
..        ...     ...  ...    ...    ...    ...      ...       ...
886         0       2    1  27.00      0      0  13.0000         2
887         1       1    0  19.00      0      0  30.0000         2
888         0       3    0  27.92      1      2  23.4500         2
889         1       1    1  26.00      0      0  30.0000         0
890         0       3    1  32.00      0      0   7.7500         1

[890 rows x 8 columns]

In [432]:
myDf

Survived  Pclass  Sex    Age  SibSp  Parch     Fare  Embarked
0           0       3    1  22.00      1      0   7.2500         2
1           1       1    0  38.00      1      0  71.2833         0
2           1       3    0  26.00      0      0   7.9250         2
3           1       1    0  35.00      1      0  53.1000         2
4           0       3    1  35.00      0      0   8.0500         2
..        ...     ...  ...    ...    ...    ...      ...       ...
886         0       2    1  27.00      0      0  13.0000         2
887         1       1    0  19.00      0      0  30.0000         2
888         0       3    0  27.92      1      2  23.4500         2
889         1       1    1  26.00      0      0  30.0000         0
890         0       3    1  32.00      0      0   7.7500         1

[890 rows x 8 columns]

In [433]:
mytrain,mytest=train_test_split(myDf,test_size=0.2,random_state=42)
mytrainx=mytrain.drop("Survived",axis=1)
mytrainy=mytrain.loc[:,"Survived"]
mytestx=mytest.drop("Survived",axis=1)
mytesty=mytest.loc[:,"Survived"]

In [434]:
mytrainx

Pclass  Sex    Age  SibSp  Parch     Fare  Embarked
709       3    1  30.73      1      1  15.2458         0
239       2    1  33.00      0      0  12.2750         2
382       3    1  32.00      0      0   7.9250         2
793       1    1  30.73      0      0  30.6958         0
673       2    1  31.00      0      0  13.0000         2
..      ...  ...    ...    ...    ...      ...       ...
106       3    0  21.00      0      0   7.6500         2
270       1    1  30.73      0      0  31.0000         2
861       2    1  21.00      1      0  11.5000         2
436       3    0  21.00      2      2  34.3750         2
102       1    1  21.00      0      1  77.2875         2

[712 rows x 7 columns]

In [435]:
mylogisticRegression=LogisticRegression()
mymodel=mylogisticRegression.fit(mytrainx,mytrainy)
mypredict=mymodel.predict(mytestx)
mypredict

array([0, 1, 1, 0, 0, 0, 0, 1, 0, 0, 1, 1, 1, 0, 0, 0, 0, 0, 1, 1, 0, 0,
       0, 1, 0, 0, 0, 1, 0, 0, 0, 1, 0, 0, 0, 1, 1, 0, 1, 0, 0, 0, 0, 0,
       0, 1, 1, 0, 1, 1, 0, 1, 0, 1, 1, 1, 1, 0, 0, 1, 0, 1, 1, 0, 0, 0,
       0, 0, 1, 1, 0, 1, 1, 0, 0, 0, 1, 1, 0, 0, 0, 1, 1, 0, 0, 0, 0, 0,
       1, 0, 0, 1, 1, 0, 0, 0, 0, 0, 0, 1, 0, 0, 1, 0, 1, 1, 1, 1, 1, 1,
       0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 1, 1, 0, 1, 1, 1, 0, 0, 1, 0, 0, 0,
       0, 0, 1, 1, 0, 1, 1, 0, 0, 1, 1, 1, 1, 1, 0, 1, 0, 1, 0, 1, 1, 0,
       1, 0, 1, 0, 1, 1, 0, 1, 1, 0, 0, 0, 1, 0, 0, 1, 1, 0, 1, 0, 0, 0,
       1, 1])

In [436]:
confusion_matrix(mypredict,mytesty)

array([[87, 14],
       [15, 62]])

In [437]:
print(classification_report(mypredict,mytesty))

              precision    recall  f1-score   support

           0       0.85      0.86      0.86       101
           1       0.82      0.81      0.81        77

    accuracy                           0.84       178
   macro avg       0.83      0.83      0.83       178
weighted avg       0.84      0.84      0.84       178



In [438]:
sonX=pd.concat([mytrainx,mytestx])
sonY=pd.concat([mytrainy,mytesty])



In [439]:
mymodel=mylogisticRegression.fit(sonX,sonY)

Faredeki aykiri degerleri cikarip modeli Logistic ile egitince en iyi degeri aldim buna gore egittim modelimi

In [440]:
testDf=pd.read_csv("test .csv")

In [441]:
testDf

PassengerId  Pclass                                          Name  \
0            892       3                              Kelly, Mr. James   
1            893       3              Wilkes, Mrs. James (Ellen Needs)   
2            894       2                     Myles, Mr. Thomas Francis   
3            895       3                              Wirz, Mr. Albert   
4            896       3  Hirvonen, Mrs. Alexander (Helga E Lindqvist)   
..           ...     ...                                           ...   
413         1305       3                            Spector, Mr. Woolf   
414         1306       1                  Oliva y Ocana, Dona. Fermina   
415         1307       3                  Saether, Mr. Simon Sivertsen   
416         1308       3                           Ware, Mr. Frederick   
417         1309       3                      Peter, Master. Michael J   

        Sex   Age  SibSp  Parch              Ticket      Fare Cabin Embarked  
0      male  34.5      0      0              330911    7.8292   NaN        Q  
1    female  47.0      1      0              363272    7.0000   NaN        S  
2      male  62.0      0      0              240276    9.6875   NaN        Q  
3      male  27.0      0      0              315154    8.6625   NaN        S  
4    female  22.0      1      1             3101298   12.2875   NaN        S  
..      ...   ...    ...    ...                 ...       ...   ...      ...  
413    male   NaN      0      0           A.5. 3236    8.0500   NaN        S  
414  female  39.0      0      0            PC 17758  108.9000  C105        C  
415    male  38.5      0      0  SOTON/O.Q. 3101262    7.2500   NaN        S  
416    male   NaN      0      0              359309    8.0500   NaN        S  
417    male   NaN      1      1                2668   22.3583   NaN        C  

[418 rows x 11 columns]

In [442]:
testDf["Embarked"]=cevir.fit_transform(testDf["Embarked"])

In [443]:
testDf

PassengerId  Pclass                                          Name  \
0            892       3                              Kelly, Mr. James   
1            893       3              Wilkes, Mrs. James (Ellen Needs)   
2            894       2                     Myles, Mr. Thomas Francis   
3            895       3                              Wirz, Mr. Albert   
4            896       3  Hirvonen, Mrs. Alexander (Helga E Lindqvist)   
..           ...     ...                                           ...   
413         1305       3                            Spector, Mr. Woolf   
414         1306       1                  Oliva y Ocana, Dona. Fermina   
415         1307       3                  Saether, Mr. Simon Sivertsen   
416         1308       3                           Ware, Mr. Frederick   
417         1309       3                      Peter, Master. Michael J   

        Sex   Age  SibSp  Parch              Ticket      Fare Cabin  Embarked  
0      male  34.5      0      0              330911    7.8292   NaN         1  
1    female  47.0      1      0              363272    7.0000   NaN         2  
2      male  62.0      0      0              240276    9.6875   NaN         1  
3      male  27.0      0      0              315154    8.6625   NaN         2  
4    female  22.0      1      1             3101298   12.2875   NaN         2  
..      ...   ...    ...    ...                 ...       ...   ...       ...  
413    male   NaN      0      0           A.5. 3236    8.0500   NaN         2  
414  female  39.0      0      0            PC 17758  108.9000  C105         0  
415    male  38.5      0      0  SOTON/O.Q. 3101262    7.2500   NaN         2  
416    male   NaN      0      0              359309    8.0500   NaN         2  
417    male   NaN      1      1                2668   22.3583   NaN         0  

[418 rows x 11 columns]

In [444]:
testDf.drop("Ticket",axis=1,inplace=True)

In [445]:
testDf.drop(["Name"],axis=1,inplace=True)

In [446]:
testDf.drop("Cabin",axis=1,inplace=True)

In [447]:
testDf

PassengerId  Pclass     Sex   Age  SibSp  Parch      Fare  Embarked
0            892       3    male  34.5      0      0    7.8292         1
1            893       3  female  47.0      1      0    7.0000         2
2            894       2    male  62.0      0      0    9.6875         1
3            895       3    male  27.0      0      0    8.6625         2
4            896       3  female  22.0      1      1   12.2875         2
..           ...     ...     ...   ...    ...    ...       ...       ...
413         1305       3    male   NaN      0      0    8.0500         2
414         1306       1  female  39.0      0      0  108.9000         0
415         1307       3    male  38.5      0      0    7.2500         2
416         1308       3    male   NaN      0      0    8.0500         2
417         1309       3    male   NaN      1      1   22.3583         0

[418 rows x 8 columns]

In [448]:
testDf.isnull().sum()

PassengerId     0
Pclass          0
Sex             0
Age            86
SibSp           0
Parch           0
Fare            1
Embarked        0
dtype: int64

In [449]:
testDf["Fare"]=testDf["Fare"].fillna(np.round(testDf["Fare"].mean(),2))
testDf[testDf['Sex'] == 'male'] = testDf[testDf['Sex'] == 'male'].fillna(np.round(testDf[testDf['Sex'] == 'male']["Age"].mean(),2))
testDf[testDf['Sex'] == 'female'] = testDf[testDf['Sex'] == 'female'].fillna(np.round(testDf[testDf['Sex'] == 'female']["Age"].mean(),2))


In [450]:
testDf.isnull().sum()

PassengerId    0
Pclass         0
Sex            0
Age            0
SibSp          0
Parch          0
Fare           0
Embarked       0
dtype: int64

In [451]:
testDf["Sex"]=cevir.fit_transform(testDf["Sex"])

In [452]:
testDf

PassengerId  Pclass  Sex    Age  SibSp  Parch      Fare  Embarked
0            892       3    1  34.50      0      0    7.8292         1
1            893       3    0  47.00      1      0    7.0000         2
2            894       2    1  62.00      0      0    9.6875         1
3            895       3    1  27.00      0      0    8.6625         2
4            896       3    0  22.00      1      1   12.2875         2
..           ...     ...  ...    ...    ...    ...       ...       ...
413         1305       3    1  30.27      0      0    8.0500         2
414         1306       1    0  39.00      0      0  108.9000         0
415         1307       3    1  38.50      0      0    7.2500         2
416         1308       3    1  30.27      0      0    8.0500         2
417         1309       3    1  30.27      1      1   22.3583         0

[418 rows x 8 columns]

In [453]:
PassengerID=testDf["PassengerId"]

In [454]:
testDf.drop("PassengerId",axis=1,inplace=True)

In [455]:
predictTest=mymodel.predict(testDf)

In [456]:
predictTest

array([0, 0, 0, 0, 1, 0, 1, 0, 1, 0, 0, 0, 1, 0, 1, 1, 0, 0, 1, 1, 0, 0,
       1, 1, 1, 0, 1, 0, 0, 0, 0, 0, 0, 0, 1, 0, 1, 1, 0, 0, 0, 0, 0, 1,
       1, 0, 0, 0, 1, 0, 0, 0, 1, 1, 0, 0, 0, 0, 0, 1, 0, 0, 0, 1, 1, 1,
       1, 0, 1, 1, 1, 0, 1, 1, 1, 1, 0, 1, 0, 1, 0, 0, 0, 0, 0, 0, 1, 1,
       1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 0, 0, 1, 0, 0, 0, 0, 0,
       0, 1, 1, 1, 1, 0, 0, 1, 1, 1, 1, 0, 1, 0, 0, 1, 0, 0, 0, 0, 0, 0,
       1, 0, 0, 0, 0, 0, 1, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0,
       0, 0, 1, 1, 0, 1, 1, 0, 1, 0, 0, 1, 0, 0, 1, 1, 0, 0, 0, 0, 0, 1,
       1, 0, 1, 1, 0, 0, 1, 0, 1, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1,
       0, 1, 1, 0, 0, 1, 0, 1, 1, 0, 1, 0, 0, 0, 0, 0, 0, 0, 1, 0, 1, 0,
       1, 0, 1, 0, 1, 1, 0, 1, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 1, 1, 1, 1,
       0, 0, 0, 0, 1, 0, 1, 1, 1, 0, 1, 0, 0, 0, 0, 0, 1, 0, 0, 0, 1, 1,
       0, 0, 0, 0, 1, 0, 0, 0, 1, 1, 0, 1, 0, 0, 0, 0, 1, 0, 1, 1, 1, 0,
       0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 1, 0, 0, 0, 0,

In [457]:
sample_submission2=pd.DataFrame({"PassengerId":PassengerID,"Survived":predictTest})

In [458]:
sample_submission2.to_csv('submissionlast2.csv', index=False)